# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03896ccf213eedd857794f6e653932e581a6f462e4c1b1825cc5e19018bfd071a57fd326aa0ca4c8e73773f6124376e91de242c03372c4a5bf0fb372cbaa0d87

test:
  secret_key_base: 2fcb32537b0c1b41f192cf3d2e837564c0fdde01007cbe9538eb698bb7db165ee1f30f63f0bff90e56b5f2c920d880df6e9bfae536995eb4f547e75bc62187af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
